COMMAND_ENABLE = no
COMBO_ENABLE = yes
TAP_DANCE_ENABLE = no
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
ENCODER_ENABLE = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
WPM_ENABLE = no
CAPS_WORD_ENABLE = yes

# Userspace options
USER_MOUSE_JIGGLE_ENABLE = no
USER_SECRETS_ENABLE = yes
USER_SUPER_ALT_TAB_ENABLE = no
DYNAMIC_MACRO_ENABLE = no
